<?php $_config_vars = array (
  'heading_reviews' => 'Kundenrezensionen:',
  'heading_product_reviews' => 'Rezensionen zu: ',
  'heading_reviews_write' => 'Was meinen Sie?',
  'text_input' => 'Ihre Meinung:',
  'text_author' => 'Autor:',
  'text_rating' => 'Bewertung:',
  'text_all' => 'Zeige alle Rezensionen',
  'title_nr' => 'Nr.',
  'title_author' => 'Autor',
  'title_rating' => 'Bewertung',
  'title_date' => 'Datum',
  'text_date' => 'Datum:',
  'text_text' => 'Rezension:',
  'text_product' => 'Artikel:',
  'text_note' => '<font color="#ff0000"><strong>ACHTUNG:</strong></font> HTML wird nicht unterst&uuml;tzt!',
  'text_bad' => 'SCHLECHT',
  'text_good' => 'SEHR GUT',
); ?>